sylius_grid:
    grids:
        loevgaard_sylius_brand_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: Loevgaard\SyliusBrandPlugin\Entity\Brand
            fields:
                name:
                    type: string
                    label: loevgaard_sylius_brand.ui.name
                slug:
                    type: string
                    label: loevgaard_sylius_brand.ui.slug
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete