sylius_grid:
    grids:
        loevgaard_sylius_brand_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: "%loevgaard_sylius_brand.model.brand.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                name: asc
            fields:
                image:
                    type: twig
                    label: loevgaard_sylius_brand.ui.image
                    path: .
                    options:
                        template: "@LoevgaardSyliusBrandPlugin/Grid/Field/image.html.twig"
                name:
                    type: string
                    label: loevgaard_sylius_brand.ui.name
                    sortable: ~
                code:
                    type: string
                    label: loevgaard_sylius_brand.ui.code
                    sortable: ~
            filters:
                search:
                    type: string
                    options:
                        fields: [code, name]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
