sylius_resource:
    resources:
        loevgaard_sylius_brand.brand:
            driver: doctrine/orm
            classes:
                model: Loevgaard\SyliusBrandPlugin\Entity\Brand
                interface: Loevgaard\SyliusBrandPlugin\Entity\BrandInterface
                form: Loevgaard\SyliusBrandPlugin\Form\Type\BrandType

        loevgaard_sylius_brand.brand_image:
            classes:
                model: Loevgaard\SyliusBrandPlugin\Entity\BrandImage
                form: Loevgaard\SyliusBrandPlugin\Form\Type\BrandImageType