imports:
    - "@LoevgaardSyliusBrandPlugin/Resources/config/grids/loevgaard_sylius_brand_admin_brand.yml"
    - "@LoevgaardSyliusBrandPlugin/Resources/config/grids/loevgaard_sylius_brand_admin_api_brand.yml"
    - "@LoevgaardSyliusBrandPlugin/Resources/config/grids/loevgaard_sylius_brand_admin_api_brand_image.yml"

jms_serializer:
    metadata:
        directories:
            loevgaard-sylius-brand:
                namespace_prefix: "Loevgaard\\SyliusBrandPlugin\\Model"
                path: "@LoevgaardSyliusBrandPlugin/Resources/config/serializer"
